---
parent: ./.kitchen.parent.yml

# Configure to run on the CI machine (e.g. - Travis CI)
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>
